name: jan_sampark
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2
  http: ^0.13.3
  file_picker: ^4.2.7
  image_picker: ^0.8.4+7

flutter:

  fonts:
    - family: Jacques Francois
      fonts:
        - asset: assets/fonts/JacquesFrancois-Regular.ttf
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
flutter_icons:
  image_path: "assets/images/logo.png" 
  android: true
  ios: true
  remove_alpha_ios: true